export const enum CollateralPropertyType {
  BUILDING = 'BUILDING',
  LAND = 'LAND',
  REALESTATECERTIFICATE = 'REALESTATECERTIFICATE',
  SPOT = 'SPOT',
  COMPARISON = 'COMPARISON',
  VEHICLE = 'VEHICLE',
  MACHINE = 'MACHINE',
  GENERAL = 'GENERAL',
}
