export enum RequestSlikStatus {
  DRAFT = 'SLIK_DRAFT',
  APPROVAL_BU = 'SLIK_APPROVAL_BU',
  APPROVAL_SLIK = 'SLIK_APPROVAL',
  CHECKING = 'SLIK_CHECKING',
  VERIFY = 'SLIK_VERIFY',
  RETURN_TO_RM = 'SLIK_RETURN_TO_RM',
  CANCEL = 'SLIK_CANCEL',
  COMPLETE = 'SLIK_COMPLETE',
}
