export enum STATUS {
  NEW = 'NEW',
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  RELEASE = 'RELEASE',
  ASSIGNED = 'ASSIGNED',
  ASSIGNMENT = 'ASSIGNMENT',
  VISITED = 'VISITED',
  APPROVAL_TL = 'APPROVAL_TL',
  APPROVAL_DEPT_HEAD = 'APPROVAL_DEPT_HEAD',
  APPROVAL_DH = 'APPROVAL_DH',
  RETURNTORM = 'RETURN_TO_RM',
  RETURNTOADMIN = 'RETURN_TO_ADMIN',
  APPROVE = 'APPROVED',
}

export enum STATUS_PARAMETER {
  ACTIVE = 'ACTIVE',
  DEACTIVATE = 'DEACTIVATE',
}

export enum STATUS_COLLATERAL {
  ACTIVE = 'ACTIVE',
  RELEASE = 'RELEASE',
  NEW = 'NEW',
  EXISTING = 'EXISTING',
  TO_BE_RELEASED = 'TO BE RELEASED',
  CANCEL = 'CANCEL',
}
