export enum STATUS {
  NEW = 'NEW',
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  RELEASE = 'RELEASE',
  ASSIGNED = 'ASSIGNED',
  ASSIGNMENT = 'ASSIGNMENT',
  VISITED = 'VISITED',
}

export enum STATUS_COLLATERAL {
  NEW = 'NEW',
  ACTIVE = 'ACTIVE',
  RELEASED = 'RELEASED',
}
