import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { ApplicationConfigService } from 'app/core/config/application-config.service';
import { AbstractEntityService } from 'app/shared/base/abstract-entity.service';
import { MICROSERVICENAME } from 'app/shared/constants/config.constants';
import { Observable, from } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class MasterDocumentTermService extends AbstractEntityService<any> {
  constructor(protected http: HttpClient, protected applicationConfigService: ApplicationConfigService) {
    super(http);
    this.resourceUrl = this.applicationConfigService.getEndpointFor(MICROSERVICENAME.LOS + '/api/company-parameters');
  }
  public data = [
    {
      id: 30785,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'TRUSTEE',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.205702Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.205702Z',
      code: '01',
      name: 'TRUSTEE',
    },
    {
      id: 30784,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'LAINNYA-ASING',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.205141Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.205141Z',
      code: 'X1',
      name: 'LAINNYA-ASING',
    },
    {
      id: 30783,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PERSEROAN PERSEORANGAN',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.204608Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.204608Z',
      code: 'I3',
      name: 'PERSEROAN PERSEORANGAN',
    },
    {
      id: 30782,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PERSEORANGAN',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.203948Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.203948Z',
      code: 'I2',
      name: 'NASABAH KELOMPOK (PERSEORANGAN)',
    },
    {
      id: 30781,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'LIMITED',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.203522Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.203522Z',
      code: 'C9',
      name: 'LIMITED',
    },
    {
      id: 30780,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'FIRMA',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.202930Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.202930Z',
      code: 'C4',
      name: 'FIRMA',
    },
    {
      id: 30779,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'EMKL',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.202368Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.202368Z',
      code: 'C3',
      name: 'EKSPEDISI MUATAN KAPAL LAUT (EMKL)',
    },
    {
      id: 30778,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'BADAN USAHA LAINNYA',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.201858Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.201858Z',
      code: 'C22',
      name: 'BADAN USAHA LAINNYA',
    },
    {
      id: 30777,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'UNIT DAGANG KREDIT PEDESAAN',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.201390Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.201390Z',
      code: 'C20',
      name: 'UNIT DAGANG KREDIT PEDESAAN',
    },
    {
      id: 30776,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'BADAN USAHA',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.200930Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.200930Z',
      code: 'C2',
      name: 'NASABAH KELOMPOK (BADAN USAHA)',
    },
    {
      id: 30775,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'UD',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.200402Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.200402Z',
      code: 'C19',
      name: 'USAHA DAGANG (UD)',
    },
    {
      id: 30774,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PERUSAHAAN UMUM',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.199998Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.199998Z',
      code: 'C13',
      name: 'PERUSAHAAN UMUM',
    },
    {
      id: 30773,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PERSEKUTUAN PERDATA',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.199645Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.199645Z',
      code: 'C12',
      name: 'PERSEKUTUAN PERDATA',
    },
    {
      id: 30772,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'NAMLOOSE VENOTSCHAAP',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.199186Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.199186Z',
      code: 'C11',
      name: 'NAMLOOSE VENOTSCHAAP',
    },
    {
      id: 30771,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'MASKAPAI ANDIL INDONESIA',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.198779Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.198779Z',
      code: 'C10',
      name: 'MASKAPAI ANDIL INDONESIA',
    },
    {
      id: 30770,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'FOREIGN BANK',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.198345Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.198345Z',
      code: 'B10',
      name: 'FOREIGN BANK',
    },
    {
      id: 30769,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PERUSAHAAN UMUM DAERAH',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.197784Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.197784Z',
      code: 'G5',
      name: 'PERUSAHAAN UMUM DAERAH',
    },
    {
      id: 30768,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PERUSAHAAN PERSEROAN DAERAH',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.197416Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.197416Z',
      code: 'G4',
      name: 'PERUSAHAAN PERSEROAN DAERAH',
    },
    {
      id: 30767,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PD/BUMD',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.197027Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.197027Z',
      code: 'G1',
      name: 'PERUSAHAAN DAERAH (PD/BUMD)',
    },
    {
      id: 30766,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PD/BUMD-BANK',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.196490Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.196490Z',
      code: 'B2',
      name: 'PERUSAHAAN DAERAH (PD/BUMD-BANK)',
    },
    {
      id: 30765,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'KUD',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.194871Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.194871Z',
      code: 'C8',
      name: 'KOPERASI UNIT DESA (KUD)',
    },
    {
      id: 30764,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'KOPERASI',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.194267Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.194267Z',
      code: 'C7',
      name: 'KOPERASI',
    },
    {
      id: 30763,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'INDUKSI KOPERASI',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.193739Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.193739Z',
      code: 'C6',
      name: 'INDUKSI KOPERASI',
    },
    {
      id: 30762,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'KOPERASI GABUNGAN',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.193153Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.193153Z',
      code: 'C5',
      name: 'KOPERASI GABUNGAN',
    },
    {
      id: 30761,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'KUD PUSAT',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.192646Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.192646Z',
      code: 'C18',
      name: 'KOPERASI UNIT DESA (KUD) PUSAT',
    },
    {
      id: 30760,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'KOPERASI PUSAT',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.192082Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.192082Z',
      code: 'C17',
      name: 'KOPERASI PUSAT',
    },
    {
      id: 30759,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'KOPERASI PRIMER',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.191523Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.191523Z',
      code: 'C14',
      name: 'KOPERASI PRIMER',
    },
    {
      id: 30758,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'BUUD',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.190928Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.190928Z',
      code: 'B1',
      name: 'BADAN USAHA UNIT DESA (BUUD)',
    },
    {
      id: 30757,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'YAYASAN',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.190366Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.190366Z',
      code: 'C21',
      name: 'YAYASAN',
    },
    {
      id: 30756,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'CV',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.189878Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.189878Z',
      code: 'C1',
      name: 'COMMANDITER VENOTSCHAAP (CV)',
    },
    {
      id: 30755,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'BUMN',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.189079Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.189079Z',
      code: 'G2',
      name: 'PERSERO / BADAN USAHA MILIK NEGARA (BUMN)',
    },
    {
      id: 30754,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PT',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.188065Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.188065Z',
      code: 'C16',
      name: 'PERSEROAN TERBATAS (PT)',
    },
    {
      id: 30753,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'BANK BPR',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.187266Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.187266Z',
      code: 'B9',
      name: 'BANK BPR',
    },
    {
      id: 30752,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'BUMN PT-BANK',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.185803Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.185803Z',
      code: 'B4',
      name: 'PERSERO / BADAN USAHA MILIK NEGARA (BUMN) (PT-BANK)',
    },
    {
      id: 30751,
      statusId: null,
      statusCode: null,
      statusDescription: null,
      abbreviation: 'PT-BANK',
      sequence: null,
      parameterCategoryId: null,
      parameterCategoryDescription: null,
      createdBy: 'system',
      createdDate: '2024-01-16T10:44:16.166065Z',
      lastModifiedBy: 'system',
      lastModifiedDate: '2024-01-16T10:44:16.166065Z',
      code: 'B3',
      name: 'PERSEROAN TERBATAS (PT-BANK)',
    },
  ];

  getMasterDocumentTerm(): Observable<any> {
    return from([this.data]);
  }
}
